<%@ Page Title="International Codes" Language="C#" MasterPageFile="~/UserMaster.Master"
    AutoEventWireup="true" CodeBehind="InternationalCodes.aspx.cs" Theme="User" Inherits="ISCS.InternationalCodes" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="content">
        <div class="inr-cont">
            <table border="0" bordercolor="red" cellspacing="0" cellpadding="4" width="100%">
                <tr>
                    <td valign="top" width="100%">
                        <h2>
                            <font size="3" color="#000000"><b>International Airport Codes
                                <br>
                                and Cities Alphabetized by City</b></font></h2>
                    </td>
                </tr>
                <tr>
                    <td valign="top" bgcolor="#EBEBEB" width="100%" align="left">
                        <blockquote>
                            <pre>
AUH     ABU DHABI, U. A. E.
ACA     ACAPULCO, MEXICO
AMM     AMMAN , JORDAN
AMS     AMSTERDAM, NETHERLANDS
ASU     ASUNCION, PARAGUAY
ATH     ATHENS, GREECE
AKL     AUCKLAND , NEW ZEALAND
BAH     BAHRAIN, BAHRAIN
BKK     BANGKOK, THAILAND
BCN     BARCELONA, SPAIN
PEK     BEIJING, CHINA
BFS     BELFAST, NORTHERN IRELAND, U.K
BJY     BELGRADE, YUGOSLAVIA
BZE     BELIZE CITY, BELIZE
BER     BERLIN, GERMANY
BIM     BIMINI, BAHAMAS
BOG     BOGOTA, COLUMBIA
BOM     BOMBAY, INDIA
CGN     BONN, GERMANY
BRU     BRUSSELS, BELGIUM
OTP     BUCHAREST, ROMANIA
BUD     BUDAPEST, HUNGARY
EZE     BUENOS AIRES, ARGENTINA
YYC     CALGARY, CANADA
CUN     CANCUN, MEXICO
CPT     CAPE TOWN , SOUTH AFRICA
CCS     CARACAS, VENEZUELA
CMN     CASABLANCA, MOROCCO
CMB     COLOMBO, SRI LANKA
CZM     COZUMEL, MEXICO
DOM     DOMINICA, DOMINICA
DUB     DUBLIN, IRELAND
DUS     DUSSELDORF, GERMANY
FRA     FRANKFURT, GERMANY
GVA     GENEVA, SWITZERLAND
GLA     GLASGOW, UNITED KINGDOM
GOT     GOTHENBURG, SWEDEN
GHB     GOVERNORS HARBOUR, BAHAMAS
GDL     GUADALAJARA, MEXICO
GUM     GUAM
GUA     GUATEMALA CITY, GUATEMALA
GYE     GUAYAQUIL, ECUADOR
YHZ     HALIFAX, NS, CANADA
HAM     HAMBURG, GERMANY
HAN     HANOI, VIETNAM
HEL     HELSINKI, FINLAND
HIW     HIROSHIMA, JAPAN
HKG     HONG KONG, HONG KONG
HUX     HUATULCO, MEXICO
IST     ISTANBUL, TURKEY
ZIH     IXTAPA, MEXICO
CGK     JAKARTA, INDONESIA
JNB     JOHANNESBURG, SOUTH AFRICA
KBP     KIEV, UKRAINE
KIN     KINGSTON, JAMAICA
BJX     LEON, MEXICO
LIM     LIMA, PERU
LIS     LISBON, PORTUGAL
LGW     LONDON (GATWICK), U.K.
LHR     LONDON (HEATHROW), U.K.
SJD     LOS CABOS, MEXICO
LYN     LYON, FRANCE
MAD     MADRID, SPAIN
MAN     MANAGUA, NICARAGUA
MAN     MANCHESTER, ENGLAND
MNL     MANILA, PHILIPPINES
MZT     MAZATLAN, MEXICO
MEL     MELBOURNE, VICTORIA,AUSTRALIA
MEX     MEXICO CITY, MEXICO
MXP     MILAN (MALPENSA), ITALY
MTY     MONTERREY, MEXICO
YUL     MONTREAL, CANADA
SVO     MOSCOW (SHEREMETYEVO),RUSSIA
MUC     MUNICH, GERMANY
NGO     NAGOYA, JAPAN
NBO     NAIROBI, KENYA
NAP     NAPLES, ITALY
NAS     NASSAU, BAHAMAS
NCE     NICE, FRANCE
KIX     OSAKA, JAPAN
OSL     OSLO, NORWAY
YOW     OTTAWA, CANADA
PTY     PANAMA CITY, PANAMA
PID     PARADISE ISLAND, BAHAMAS
CDG     PARIS (CHARLES DE GAULLE),FRANCE
ORY     PARIS (ORLY), FRANCE
PSE     PONCE, PUERTO RICO
PRG     PRAGUE, CZECH REPUBLIC
PVR     PUERTO VALLARTA, MEXICO
YQB     QUEBEC, CANADA
RKV     REYKJAVIK, ICELAND
GIG     RIO DE JANEIRO, RJ, BRAZIL
FCO     ROME (L.DA VINCI/FIUMICINO), ITALY
SCL     SANTIAGO DE CHILE, CHILE
SDQ     SANTO DOMINGO, DOMINICAN REPUBLIC
GRU     SAO PAULO, SP, BRAZIL
CTX     SAPPORO, JAPAN
SEL     SEOUL, KOREA
SNN     SHANNON, IRELAND
SIN     SINGAPORE, SINGAPORE
STX     ST. CROIX, U.S. VIRGIN ISLANDS
SLU     ST. LUCIA, ST. LUCIA
SXM     ST. MAARTEN, NETHERLANDS ANTILLES
LED     ST. PETERSBURG, RUSSIA
ARN     STOCKHOLM , SWEDEN
STR     STUTTGART, GERMANY
SYD     SYDNEY, AUSTRALIA
TPE     TAIPEI, TAIWAN
TLV     TEL AVIV, ISRAEL
NRT     TOKYO (NARITA), JAPAN
YYZ     TORONTO, CANADA
EIS     TORTOLA, B V I
YVR     VANCOUVER, BC, CANADA
VIE     VIENNA, AUSTRIA
WAW     WARSAW, POLAND
XIY     XIAN XIANYANG, CHINA
ZRH     ZURICH, SWITZERLAND</pre>
                            <h2>
                                <font size="3" color="#000000"><b>International Airport Codes
                                    <br>
                                    and Cities Alphabetized by Code</b></font></h2>
                            <pre>ACA     ACAPULCO, MEXICO
AKL     AUCKLAND , NEW ZEALAND
AMM     AMMAN , JORDAN
AMS     AMSTERDAM, NETHERLANDS
ARN     STOCKHOLM , SWEDEN
ASU     ASUNCION, PARAGUAY
ATH     ATHENS, GREECE
AUH     ABU DHABI, UNITED ARAB EMIRATES
BAH     BAHRAIN, BAHRAIN
BCN     BARCELONA, SPAIN
BER     BERLIN, GERMANY
BFS     BELFAST, NORTHERN IRELAND, U.K
BIM     BIMINI, BAHAMAS
BJX     LEON, MEXICO
BJY     BELGRADE, YUGOSLAVIA
BKK     BANGKOK, THAILAND
BOG     BOGOTA, COLUMBIA
BOM     BOMBAY, INDIA
BRU     BRUSSELS, BELGIUM
BUD     BUDAPEST, HUNGARY
BZE     BELIZE CITY, BELIZE
CCS     CARACAS, VENEZUELA
CDG     PARIS (CHARLES DE GAULLE),FRANCE
CGK     JAKARTA, INDONESIA
CGN     BONN, GERMANY
CMB     COLOMBO, SRI LANKA
CMN     CASABLANCA, MOROCCO
CPT     CAPE TOWN , SOUTH AFRICA
CTX     SAPPORO, JAPAN
CUN     CANCUN, MEXICO
CZM     COZUMEL, MEXICO
DOM     DOMINICA, DOMINICA
DUB     DUBLIN, IRELAND
DUS     DUSSELDORF, GERMANY
EIS     TORTOLA, BRITISH VIRGIN ISLANDS
EZE     BUENOS AIRES, ARGENTINA
FCO     ROME (L.DA VINCI/FIUMICINO),ITALY
FRA     FRANKFURT, GERMANY
GDL     GUADALAJARA, MEXICO
GHB     GOVERNORS HARBOUR, BAHAMAS
GIG     RIO DE JANEIRO, RJ, BRAZIL
GLA     GLASGOW, UNITED KINGDOM
GOT     GOTHENBURG, SWEDEN
GRU     SAO PAULO, SP, BRAZIL
GUA     GUATEMALA CITY, GUATEMALA
GUM     GUAM
GVA     GENEVA, SWITZERLAND
GYE     GUAYAQUIL, ECUADOR
HAM     HAMBURG, GERMANY
HAN     HANOI, VIETNAM
HEL     HELSINKI, FINLAND
HIW     HIROSHIMA, JAPAN
HKG     HONG KONG, HONG KONG
HUX     HUATULCO, MEXICO
IST     ISTANBUL, TURKEY
JNB     JOHANNESBURG, SOUTH AFRICA
KBP     KIEV, UKRAINE
KIN     KINGSTON, JAMAICA
KIX     OSAKA, JAPAN
LED     ST. PETERSBURG, RUSSIA
LGW     LONDON (GATWICK), UNITED KINGDOM
LHR     LONDON (HEATHROW), UNITED KINGDOM
LIM     LIMA, PERU
LIS     LISBON, PORTUGAL
LYN     LYON, FRANCE
MAD     MADRID, SPAIN
MAN     MANAGUA, NICARAGUA
MAN     MANCHESTER, ENGLAND
MEL     MELBOURNE, VICTORIA, AUSTRALIA
MEX     MEXICO CITY, MEXICO
MNL     MANILA, PHILIPPINES
MTY     MONTERREY, MEXICO
MUC     MUNICH, GERMANY
MXP     MILAN (MALPENSA), ITALY
MZT     MAZATLAN, MEXICO
NAP     NAPLES, ITALY
NAS     NASSAU, BAHAMAS
NBO     NAIROBI, KENYA
NCE     NICE, FRANCE
NGO     NAGOYA, JAPAN
NRT     TOKYO (NARITA), JAPAN
ORY     PARIS (ORLY), FRANCE
OSL     OSLO, NORWAY
OTP     BUCHAREST, ROMANIA
PEK     BEIJING, CHINA
PID     PARADISE ISLAND, BAHAMAS
PRG     PRAGUE, CZECH REPUBLIC
PSE     PONCE, PUERTO RICO
PTY     PANAMA CITY, PANAMA
PVR     PUERTO VALLARTA, MEXICO
RKV     REYKJAVIK, ICELAND
SCL     SANTIAGO DE CHILE, CHILE
SDQ     SANTO DOMINGO, DOMINICAN REPUBLIC
SEL     SEOUL, KOREA
SIN     SINGAPORE, SINGAPORE
SJD     LOS CABOS, MEXICO
SLU     ST. LUCIA, ST. LUCIA
SNN     SHANNON, IRELAND
STR     STUTTGART, GERMANY
STX     ST. CROIX, U.S. VIRGIN ISLANDS
SVO     MOSCOW (SHEREMETYEVO), RUSSIA
SXM     ST. MAARTEN, NETHERLANDS ANTILLES
SYD     SYDNEY, AUSTRALIA
TLV     TEL AVIV, ISRAEL
TPE     TAIPEI, TAIWAN
VIE     VIENNA, AUSTRIA
WAW     WARSAW, POLAND
XIY     XIAN XIANYANG, CHINA
YHZ     HALIFAX, NS, CANADA
YOW     OTTAWA, CANADA
YQB     QUEBEC, CANADA
YUL     MONTREAL, CANADA
YVR     VANCOUVER, BC, CANADA
YYC     CALGARY, CANADA
YYZ     TORONTO, CANADA
ZIH     IXTAPA, MEXICO
ZRH     ZURICH, SWITZERLAND
</pre>
                        </blockquote>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</asp:Content>
