using System;

namespace EntityLayer
{
    public class PickupRequestEL
    {
        public int PickupRequestId { get; set; }
        public Int16 PickupRequestType { get; set; }
        public int PickupRequestTypeWarehouse { get; set; }
        public Int16 WarehouseRecieved { get; set; }
        public int UserId { get; set; }
        public string BrowserType { get; set; }
        public string OperatingSystem { get; set; }
        public DateTime DateCreated { get; set; }
        public int StatusId { get; set; }
        public int ShipFromLocationId { get; set; }
        public string ShipFromCompany { get; set; }
        public string ShipFromRefNumber { get; set; }
        public string ShipFromAddress { get; set; }
        public string ShipFromCity { get; set; }
        public string ShipFromState { get; set; }
        public int ShipFromStateId { get; set; }
        public int ShipFromCountryId { get; set; }
        public string ShipFromPostalCode { get; set; }
        public string ShipFromCountry { get; set; }
        public string ShipFromContact { get; set; }
        public string ShipFromPhone { get; set; }
        public string ShipFromFax { get; set; }
        public string ShipFromEmail { get; set; }
        public DateTime ShipFromDate { get; set; }
        public string ShipFromTimeReady { get; set; }
        public string ShipFromTimeNLT { get; set; }
        public int ShipToLocationId { get; set; }
        public string ShipToCompany { get; set; }
        public DateTime ShipToDate { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public int ShipToStateId { get; set; }
        public int ShipToCountryId { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToContact { get; set; }
        public string ShipToPhone { get; set; }
        public string ShipToFax { get; set; }
        public string ShipToNotifyName { get; set; }
        public string ShipToNotifyPhone { get; set; }
        public string ShipToConsigneeRefNumber { get; set; }
        public string DemensionType { get; set; }
        public string WeightType { get; set; }
        public int Qty1 { get; set; }
        public int Qty2 { get; set; }
        public int Qty3 { get; set; }
        public int Qty4 { get; set; }
        public int HazMat1 { get; set; }
        public int HazMat2 { get; set; }
        public int HazMat3 { get; set; }
        public int HazMat4 { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public int Length1 { get; set; }
        public int Length2 { get; set; }
        public int Length3 { get; set; }
        public int Length4 { get; set; }
        public int Width1 { get; set; }
        public int Width2 { get; set; }
        public int Width3 { get; set; }
        public int Width4 { get; set; }
        public int Height1 { get; set; }
        public int Height2 { get; set; }
        public int Height3 { get; set; }
        public int Height4 { get; set; }
        public int Weight1 { get; set; }
        public int Weight2 { get; set; }
        public int Weight3 { get; set; }
        public int Weight4 { get; set; }
        public string Class1 { get; set; }
        public string Class2 { get; set; }
        public string Class3 { get; set; }
        public string Class4 { get; set; }
        public decimal DeclaredValue1 { get; set; }
        public decimal DeclaredValue2 { get; set; }
        public decimal DeclaredValue3 { get; set; }
        public decimal DeclaredValue4 { get; set; }
        public string HazMatEmergencyPhone { get; set; }
        public int TransMode { get; set; }
        public string TransModeName { get; set; }
        public string TransModeService1 { get; set; }
        public string TransModeService2 { get; set; }
        public string SpecialServiceCodes { get; set; }
        public string ExportEIN { get; set; }
        public string ExportLicence { get; set; }
        public string ExportECCN { get; set; }
        public int ExportPartyTrans { get; set; }
        public string ExportIntermediateConsignee { get; set; }
        public string ExportAddress { get; set; }
        public string ExportCity { get; set; }
        public string ExportIntermediateContact { get; set; }
        public string ExportPostalCode { get; set; }
        public string ExportCountry { get; set; }
        public string ExportLoadingPort { get; set; }
        public string ExportIntermediatePhone { get; set; }
        public string ExportUnloadingPort { get; set; }
        public int ExportContanerized { get; set; }
        public string ExportAlternative { get; set; }
        public string ExportAlternativeDeliverTo { get; set; }
        public string ExportMfg1 { get; set; }
        public string ExportMfg2 { get; set; }
        public string ExportMfg3 { get; set; }
        public string ExportMfg4 { get; set; }
        public string ExportScheduleB1 { get; set; }
        public string ExportScheduleB2 { get; set; }
        public string ExportScheduleB3 { get; set; }
        public string ExportScheduleB4 { get; set; }
        public string ExportTypeOfPackage1 { get; set; }
        public string ExportTypeOfPackage2 { get; set; }
        public string ExportTypeOfPackage3 { get; set; }
        public string ExportTypeOfPackage4 { get; set; }
        public string ExportUnits1 { get; set; }
        public string ExportUnits2 { get; set; }
        public string ExportUnits3 { get; set; }
        public string ExportUnits4 { get; set; }
        public string SpecialInstructions { get; set; }
        public string GLSPaymentMethod { get; set; }
        public string GLSCertifiedCheck { get; set; }
        public string GLSBillCompany { get; set; }
        public string GLSBillAddress { get; set; }
        public string GLSBillCity { get; set; }
        public int GLSBillStateId { get; set; }
        public string BillToStateName { get; set; }
        public string GLSBillPostalCode { get; set; }
        public int GLSBillCountryId { get; set; }
        public string BillToCountryName { get; set; }
        public string GLSCarrierName { get; set; }
        public decimal GLSCubicDisplacement { get; set; }
        public decimal GLSCubicWeight { get; set; }
        public decimal GLSDimWeight1 { get; set; }
        public decimal GLSDimWeight2 { get; set; }
        public decimal GLSDimWeight3 { get; set; }
        public decimal GLSDimWeight4 { get; set; }
        public int GLSInsured { get; set; }
        public string GLSNotes { get; set; }
        public decimal GLSShippedWeight { get; set; }
        public int GLSAccountId { get; set; }
        public string GLSTrackingNumber { get; set; }
        public Int16 IsPending { get; set; }
        public decimal GLSBuyRateTransportCharge { get; set; }
        public decimal GLSBuyRateAccessorialCharge { get; set; }
        public decimal GLSBuyRateFuelCharge { get; set; }
        public decimal GLSBuyRateInsuraceCharge { get; set; }
        public decimal GLSBuyRateCodFee { get; set; }
        public decimal GLSTotalBuyRate { get; set; }
        public decimal GLSSellRateTransportCharge { get; set; }
        public decimal GLSSellRateAccessorialCharge { get; set; }
        public decimal GLSSellRateFuelCharge { get; set; }
        public decimal GLSSellRateInsuraceCharge { get; set; }
        public decimal GLSSellRateCodFee { get; set; }
        public decimal GLSTotalSellRate { get; set; }
        public decimal GLSTotalDeclaredValue { get; set; }
        public Int16 GLSKnownShipper { get; set; }
        public string GLSCarrierNameInterm { get; set; }
        public string GLSCarrierNameDelivery { get; set; }
        public string GLSCarrierNameOther { get; set; }
        public decimal GLSBuyRateTransportChargeInterm { get; set; }
        public decimal GLSBuyRateTransportChargeDelivery { get; set; }
        public decimal GLSBuyRateTransportChargeOther { get; set; }
        public decimal GLSBuyRateAccessorialChargeInterm { get; set; }
        public decimal GLSBuyRateAccessorialChargeDelivery { get; set; }
        public decimal GLSBuyRateAccessorialChargeOther { get; set; }
        public decimal GLSBuyRateFuelChargeInterm { get; set; }
        public decimal GLSBuyRateFuelChargeDelivery { get; set; }
        public decimal GLSBuyRateFuelChargeOther { get; set; }
        public int Insured { get; set; }
        public decimal InsuredValue { get; set; }
        public decimal GLSBuyRateBrokerage { get; set; }
        public decimal GLSSellRateBrokerage { get; set; }
        public decimal GLSBuyRateDuty { get; set; }
        public decimal GLSSellRateDuty { get; set; }
        public string ExportVin1 { get; set; }
        public string ExportVin2 { get; set; }
        public string ExportVin3 { get; set; }
        public string ExportVin4 { get; set; }
        public string ShippersInstructions { get; set; }
        public string DocumentsEnclosed { get; set; }
        public decimal Margin { get; set; }
        public int GLSTotalPieces { get; set; }
        public int WarehouseFlag { get; set; }
        public int SkeletonRecord { get; set; }
        public string StatusCode { get; set; }

    }
}
